${CGAL_DATA_DIR}/meshes/sphere.off ${CGAL_DATA_DIR}/meshes/elephant.off
${CGAL_DATA_DIR}/meshes/cow.off ${CGAL_DATA_DIR}/meshes/cross.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefbroken_bound-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefbroken_bound-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefP7.off  ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefQ7.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off ${CGAL_DATA_DIR}/meshes/sphere.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/t3bis.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/t3ter.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle_barycenter.off  ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/on_vertex_c.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle_barycenter.off  ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/on_edge_c.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle_triangulated.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/on_edge_c.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/c1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/c2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/b1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/b2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/d1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/d2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/ex1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle_barycenter.off  ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/on_vertex.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle_triangulated.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/on_edge.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/1poly.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/4poly.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftestsuite/big_triangle.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefopen_tet_1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefopen_tet_2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefelephant_split_1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefelephant_split_2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefc1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefc2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefc1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefc2_bis.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr6-1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr8-1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr5-2.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr7-2.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr9-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr9-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr10-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr10-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr11-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr11-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr12-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr12-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr13-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr13-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr14-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/collinear_edges/tr14-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr5-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr7-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr8-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/vertex_on_edge/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr5-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr7-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr8-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr9-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr9-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr10-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr10-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr11-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr11-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr12-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr12-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr13-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr13-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr14-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr14-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr15-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr15-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr16-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr16-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr17-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/deg/tr17-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/bugreport/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr5-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr7-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr8-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/all_cases/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr5-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr7-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr8-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr9-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr9-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr3-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr3-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr4-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr4-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr5-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr5-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr7-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr7-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr8-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/simple/tr8-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr10-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr10-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr11-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr11-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr12-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_triangles/tr12-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr3-2.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr3-1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr4-2.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr4-1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr5-2.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr5-1.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr6-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefcoplanar_segments/tr6-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_edge/ex1-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_edge/ex1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_edge/ex2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_edge/ex2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_vertex/ex1-1.off  ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_vertex/ex1-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_vertex/ex2-1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefintersection_vertex/ex2-2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftest_sets/t1.off ${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-coreftest_sets/t2.off
${CGAL_DATA_DIR}/test/Polygon_mesh_processing/data-corefbig_triangle.off ${CGAL_DATA_DIR}/meshes/elephant.off
