${CGAL_DATA_DIR}/meshes/cube.off
${CGAL_DATA_DIR}/meshes/open_cube.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/eight.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/genus1.off
${CGAL_DATA_DIR}/meshes/head.off
${CGAL_DATA_DIR}/meshes/hedra.off
${CGAL_DATA_DIR}/meshes/hedra_open.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/helmet.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/hexagon_open.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/oct.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/oni.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/square_open.off
${CGAL_DATA_DIR}/meshes/star.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/tetra.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/tetra_12f.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/tetra_6f.off
${CGAL_DATA_DIR}/meshes/triangular_hole.off
