${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test01.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test02.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test03.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test04.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test05.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test06.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test07.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test08.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test09.off
${CGAL_DATA_DIR}/test/Surface_mesh_simplification/test10.off
${CGAL_DATA_DIR}/meshes/elephant.off
